// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdQ2A7idB_mzN6cfqmVRaW4nLgAA7SmKc',
    appId: '1:134050050670:web:692b15ab7cd4e324f82c7f',
    messagingSenderId: '134050050670',
    projectId: 'new-whatsapp-jabid',
    authDomain: 'new-whatsapp-jabid.firebaseapp.com',
    storageBucket: 'new-whatsapp-jabid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcoiKvSJ-0mk5JX_IgWNR0hNDk0s2WLNg',
    appId: '1:134050050670:android:71ca94942fe521b5f82c7f',
    messagingSenderId: '134050050670',
    projectId: 'new-whatsapp-jabid',
    storageBucket: 'new-whatsapp-jabid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADanog2kH3AKIjfJTUSGYNdLuDPpQFn_Y',
    appId: '1:134050050670:ios:ae7d1477c9ee46f0f82c7f',
    messagingSenderId: '134050050670',
    projectId: 'new-whatsapp-jabid',
    storageBucket: 'new-whatsapp-jabid.appspot.com',
    iosClientId: '134050050670-aoj0bp13mo2jkv9te5auamoi350886vm.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
