// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZm2EpInYmxvtyd2cpqyX1G8cSEvosqg',
    appId: '1:767127960317:web:99bde64aa00f748b0f1c94',
    messagingSenderId: '767127960317',
    projectId: 'whatsapp-backend-15494',
    authDomain: 'whatsapp-backend-15494.firebaseapp.com',
    storageBucket: 'whatsapp-backend-15494.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj22rHP-uZU0q8ghiH68DAbq1N-G54hyU',
    appId: '1:767127960317:android:abcb6295ac4265110f1c94',
    messagingSenderId: '767127960317',
    projectId: 'whatsapp-backend-15494',
    storageBucket: 'whatsapp-backend-15494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLK14U6qi8JA7rhcalTAbBh3DJKPXACvE',
    appId: '1:767127960317:ios:aace78cde79c8bc50f1c94',
    messagingSenderId: '767127960317',
    projectId: 'whatsapp-backend-15494',
    storageBucket: 'whatsapp-backend-15494.appspot.com',
    androidClientId: '767127960317-0m0shguuk7dvog5ng4ania80pkhblqbi.apps.googleusercontent.com',
    iosClientId: '767127960317-2ks4ndhd0d1kp62oavndb9gf29aauekv.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
